---
version: "3.4"
services:
  demo.api:
    container_name: cop
    image: ${DOCKER_REGISTRY-}demoapi
    build:
      context: .
      dockerfile: Demo.Api/Dockerfile
    ports:
      - 8080:80
    depends_on:
      - sql-server-database
  sql-server-database:
    container_name: copdb
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: $${{ build.DBPASSWORD }}
      ACCEPT_EULA: Y
    ports:
      - 1433:1433
