---
name: Docker Image CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:  
      - uses: actions/checkout@v3
      - name: Install .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x       
      - name: Restore dependencies Tests
        run: dotnet restore ./Demo.Api.Tests/Demo.Api.Tests.csproj

      - name: Restore dependencies Api
        run: dotnet restore ./Demo.Api/Demo.Api.csproj
        
      - name: Build Tests
        run: dotnet build ./Demo.Api.Tests/Demo.Api.Tests.csproj -c Release

      - name: Build Api  
        run: dotnet build ./Demo.Api/Demo.Api.csproj -c Release

      - name: Replace Variables Test
        uses: microsoft/variable-substitution@v1 
        with:
          files: ./Demo.Api.Tests/bin/Release/net6.0/TestSettings.json
        env:
            AppSettings.Password: build.DBPASSWORD
            AppSettings.UserId: build.UserId
            AppSettings.Datasource: build.Datasource

      - name: Replace Variables Api
        uses: microsoft/variable-substitution@v1 
        with:
          files: ./Demo.Api/bin/Release/net6.0/appsettings.json
        env:
            AppSettings.Password: build.DBPASSWORD
            AppSettings.UserId: build.UserId
            AppSettings.Datasource: build.Datasource
        
      - name: Compose Docker Container
        run: docker compose up -d

      - name: Execute Tests
        run: dotnet test ./Demo.Api.sln
