---
name: Docker Image CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker compose up -d
        
      - name: Install .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x       
      - name: Restore dependencies
        run: dotnet restore ./Demo.Api.Tests/Demo.Api.Tests.csproj
        
      - name: Build
        run: dotnet build ./Demo.Api.Tests/Demo.Api.Tests.csproj -c Release -o /app/build

      - name: Replace Variables
        uses: microsoft/variable-substitution@v1 
        with:
          files: ./Demo.Api.Tests/bin/Release/net6.0/TestSettings.json
        env:
            AppSettings.Password: build.DBPASSWORD
        
      - name: Execute Tests
        run: dotnet test ./Demo.Api.sln
