name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker compose up -d
      
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      uses: microsoft/variable-substitution@v1
       with:
        files: 'TestSettings.json'
    env:
        password: ${{ secrets.DBPASSWORD }}
      with:
        dotnet-version: 6.0.x
     
    - name: Execute Tests
      run: dotnet test ./Demo.Api.sln
